agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiftiqiqpxn7ghrurhepquzqzk3su3x6wanlnolt2uj772fzgz574m
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeibiyn7ofdsb7fdohpoounhcmq4fqh2veuuccpb3safxl7hx6r4ieq
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeidpkg2yj6jlyzomefz3hqe7nnqdxwmr7l66hxnr2a3ybtvw4k7bi4
- fetchai/state_update:1.0.0:bafybeiboyy34msyrbw7gf3uzdyztx5rdi6je3p6npfafxpvvj3kl7o72l4
- open_aea/signing:1.0.0:bafybeighvx4vpsyspffggewidvkfq3lqbse6ap4tdewd6j5bs73ifnuaui
skills:
- fetchai/echo:0.19.0:bafybeigqa3nmawq4zn7nmcocjtdjvvcy5clq65cizro2usizd2fyaengka
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
