agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiadln5ca6tu6rzbsgjpeluf6nz5efxl3u223c3vxwgf2iynkj5n6q
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeibdcxk4ggfvedwfc64qyipcvmcdalcbbhjukukgzmci3rk5y3ktty
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeihlinyex5t3hzhkwl4wjxymkmx7vkg7k2vfkfr4sgylrmuxztccyy
- fetchai/gym:1.0.0:bafybeiclkjwiigya6pvk4bcef7kmy64fctobntj7rfi43yx6e54da6zuz4
- fetchai/state_update:1.0.0:bafybeicllubr2plh775rvju3jlmywqstdqtkbxopf6damgs53o2ubfstyq
- open_aea/signing:1.0.0:bafybeidlbuhssnfifl2xn2kngompqkmhgtu4xaxgwfphqqqukrcbf2q544
skills:
- fetchai/gym:0.20.0:bafybeigciwbtuh5x2pigkzghcaq65tnsxhermd7okzy62jq6e24qmzmfwe
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
