agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiadln5ca6tu6rzbsgjpeluf6nz5efxl3u223c3vxwgf2iynkj5n6q
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeiardoniipbbht6trvgwwoyusjwz3luyfmu2v3zmiplhywstt2s5ru
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeidpkg2yj6jlyzomefz3hqe7nnqdxwmr7l66hxnr2a3ybtvw4k7bi4
- fetchai/gym:1.0.0:bafybeictgqzq3vntvz5wmnybl33nfmwoey7ckq5tveans4cipdmtwm2bby
- fetchai/state_update:1.0.0:bafybeiboyy34msyrbw7gf3uzdyztx5rdi6je3p6npfafxpvvj3kl7o72l4
- open_aea/signing:1.0.0:bafybeighvx4vpsyspffggewidvkfq3lqbse6ap4tdewd6j5bs73ifnuaui
skills:
- fetchai/gym:0.20.0:bafybeiecsa564i5fya5lvgkzgv6z5ehm3clhx7derehaqjvud3bhokwahy
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
