agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiadln5ca6tu6rzbsgjpeluf6nz5efxl3u223c3vxwgf2iynkj5n6q
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeibmg5zg2qnakhjod2lth6hcjd66tyekt5g5b7zsf3lwxwg6w3ljtq
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeide4cvhzwohrzuk44zpnie64gjm3rwem7xrwdufvnrusgggmwe2dy
- fetchai/gym:1.0.0:bafybeifft3rinvv5ai2snys3rmwyx3swfmgdvl26e7mq3olpz4cjjb3hoi
- fetchai/state_update:1.0.0:bafybeib736dqbkd43sz5hpb3yd4kviv2b4g2okirknn3vsdo5tlykuu4bu
- open_aea/signing:1.0.0:bafybeieeg23kk6eqqsp3dlm72lbwub3qbvttgbn3yq7y2ccam7mdvgi7re
skills:
- fetchai/gym:0.20.0:bafybeibendxox7npijbsfqju74ptfl6y5b6s3ieufhiqzo44etveb6f5fq
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
