agent_name: my_first_aea
author: open_aea
version: 0.1.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiftiqiqpxn7ghrurhepquzqzk3su3x6wanlnolt2uj772fzgz574m
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeifjmpjdoichvst5h4c3qarhdvtztnvl2chrieryp24gwvkzafxn34
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeide4cvhzwohrzuk44zpnie64gjm3rwem7xrwdufvnrusgggmwe2dy
- fetchai/state_update:1.0.0:bafybeib736dqbkd43sz5hpb3yd4kviv2b4g2okirknn3vsdo5tlykuu4bu
- open_aea/signing:1.0.0:bafybeieeg23kk6eqqsp3dlm72lbwub3qbvttgbn3yq7y2ccam7mdvgi7re
skills:
- fetchai/echo:0.19.0:bafybeia6sgw3ppjl4y5hg5ha6mfqlo3hkvq7vkhonr3s4oubs2fow5ccyi
default_connection: fetchai/stub:0.21.0
default_ledger: ethereum
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
