agent_name: gym_aea
author: open_aea
version: 0.1.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiadln5ca6tu6rzbsgjpeluf6nz5efxl3u223c3vxwgf2iynkj5n6q
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeidd3izmj4lt4uflvqpl5v47bdo625w4phekdxe6z26mwtqsju3bk4
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifa7gnanyzkmb76y2xdyiinhygwvcdht7hmirfurx6gp4jx5xeshy
- fetchai/gym:1.0.0:bafybeid3peikgfjhkd3yj62ldakrkt5v5jhcbw3fdgfwzmaomo3jzqhw6a
- fetchai/state_update:1.0.0:bafybeicd7te4idd5rudfwwaj3x4itwxa3lwa55zt7xpjdum62qv24uxz3m
- open_aea/signing:1.0.0:bafybeighvx4vpsyspffggewidvkfq3lqbse6ap4tdewd6j5bs73ifnuaui
skills:
- fetchai/gym:0.20.0:bafybeibu4onupkix5ag65vgd2o6yscgx3lxmreoga5zhvrgc5aukajmudm
default_connection: fetchai/gym:0.19.0
default_ledger: ethereum
private_key_paths: {}
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
